### ISSUE TITLE
Velocity Deploy Action failed with Error: Request failed with status code 404

### ISSUE THREAD

**Issue by b-remo** [codeclimate/velocity-deploy-action#18]
`Steps to reproduce` 

1. Configured GHA to track deployment frequency in code climate. 
2. GHA used - https://github.com/codeclimate/velocity-deploy-action

Job failed post-deployment without any error message. Ensure the token being used is valid. 

`Expected` - Should be able to track the deploy information in velocity

`Actual` - Failed with status code 404.

Error screenshot for reference.
 
![Screenshot 2021-08-04 at 3 56 16 PM](https://user-images.githubusercontent.com/74281727/128166614-efc92116-ba49-451e-a52f-f90c602f871b.png)

**Comment by davehenton** [comment]
@b-remo thanks for reaching out! To further assist, please send us a note to velocity-support@codeclimate.com. 

Please include: 
- The name of your Velocity org
- The name of your repo

We'll be standing by to take a closer look 👍 .
